SRC = aiger_language.cpp

include ../config.inc
include ../common

CLEANFILES = 

all: aiger$(LIBEXT)

###############################################################################

aiger$(LIBEXT): $(OBJ)
	$(LINKLIB)

