SRC = aiger_language.cpp

include ../config.inc
include ../common

CLEANFILES = aiger$(LIBEXT)

all: aiger$(LIBEXT)

###############################################################################

aiger$(LIBEXT): $(OBJ)
	$(LINKLIB)

