#!/bin/bash

make
strip ebmc.exe

VERSION=`./ebmc.exe --version`
VERSION_FILE=`echo $VERSION | sed "y/./-/"`

echo $VERSION_FILE

mkdir /tmp/ebmc-dist
cp ./ebmc.exe /tmp/ebmc-dist/
cp ~/progr/cbmc/trunk/LICENSE /tmp/ebmc-dist/LICENSE.txt
unix2dos /tmp/ebmc-dist/LICENSE.txt
cp ./README /tmp/ebmc-dist/README.txt
unix2dos /tmp/ebmc-dist/README.txt
cd /tmp/ebmc-dist
zip -9 ebmc-${VERSION_FILE}-win.zip ebmc.exe LICENSE.txt README.txt

echo Copying.
scp ebmc-${VERSION_FILE}-win.zip kroening@dkr-srv.cs.ox.ac.uk:/srv/www/cprover.org/ebmc/download/

cd /tmp
rm -R /tmp/ebmc-dist
