/*******************************************************************\

Module: EBMC's Solvers

Author: Daniel Kroening, kroening@kroening.com

\*******************************************************************/

#include <fstream>
#include <iostream>

#include <util/cmdline.h>

#include <solvers/flattening/boolbv.h>
#include <solvers/sat/dimacs_cnf.h>
#include <solvers/sat/satcheck.h>
#include <solvers/smt2/smt2_dec.h>

#ifdef HAVE_PROVER
#include <prover/prover_sat.h>
#include <prover/lifter.h>
#endif

#include "ebmc_base.h"
#include "ebmc_version.h"
#include "show_formula_solver.h"

/*******************************************************************\

Function: ebmc_baset::do_dimacs

  Inputs:

 Outputs:

 Purpose: invoke main modules

\*******************************************************************/

int ebmc_baset::do_dimacs()
{
  dimacs_cnft dimacs_cnf{*message_handler};

  int result = do_bit_level_bmc(dimacs_cnf, true);
  if(result!=0) return result;

  statistics() << dimacs_cnf.no_variables() << " variables and "
               << dimacs_cnf.no_clauses() << " clauses" << eom;

  if(cmdline.isset("outfile"))
  {
    const std::string filename=cmdline.get_value("outfile");
    std::ofstream out(filename.c_str());
  
    if(!out)
    {
      error() << "Failed to open `"
              << filename
              << "'" << messaget::eom;
      return 1;
    }

    dimacs_cnf.write_dimacs_cnf(out);
  }
  else
    dimacs_cnf.write_dimacs_cnf(std::cout);

  return 0;
}

/*******************************************************************\

Function: ebmc_baset::do_smt2

  Inputs:

 Outputs:

 Purpose:

\*******************************************************************/

int ebmc_baset::do_smt2()
{
  const namespacet ns(transition_system.symbol_table);

  if(cmdline.isset("outfile"))
  {
    const std::string filename=cmdline.get_value("outfile");
    std::ofstream out(filename.c_str());

    if(!out)
    {
      std::cerr << "Failed to open `"
                << filename
                << "'" << '\n';
      return 1;
    }

    smt2_convt smt2_conv(
      ns,
      "ebmc",
      "Generated by EBMC " EBMC_VERSION,
      "QF_AUFBV",
      smt2_convt::solvert::Z3,
      out);

    return do_word_level_bmc(smt2_conv, true);
  }

  smt2_convt smt2_conv(
    ns,
    "ebmc",
    "Generated by EBMC " EBMC_VERSION,
    "QF_AUFBV",
    smt2_convt::solvert::Z3,
    std::cout);

  return do_word_level_bmc(smt2_conv, true);
}

/*******************************************************************\

Function: ebmc_baset::do_show_formula

  Inputs:

 Outputs:

 Purpose:

\*******************************************************************/

int ebmc_baset::do_show_formula()
{
  const namespacet ns(transition_system.symbol_table);

  if(cmdline.isset("outfile"))
  {
    const std::string filename = cmdline.get_value("outfile");
    std::ofstream out(filename);

    if(!out)
    {
      std::cerr << "Failed to open `" << filename << "'" << '\n';
      return 1;
    }

    show_formula_solvert show_formula_solver(out);
    return do_word_level_bmc(show_formula_solver, true);
  }

  show_formula_solvert show_formula_solver;
  return do_word_level_bmc(show_formula_solver, true);
}

/*******************************************************************\

Function: ebmc_baset::do_mathsat

  Inputs:

 Outputs:

 Purpose:

\*******************************************************************/

int ebmc_baset::do_mathsat()
{
  const namespacet ns(transition_system.symbol_table);

  smt2_dect smt2_dec(
    ns,
    "ebmc",
    "Generated by EBMC " EBMC_VERSION,
    "QF_AUFBV",
    smt2_dect::solvert::MATHSAT,
    get_message_handler());

  return do_word_level_bmc(smt2_dec, false);
}

/*******************************************************************\

Function: ebmc_baset::do_z3

  Inputs:

 Outputs:

 Purpose:

\*******************************************************************/

int ebmc_baset::do_z3()
{
  const namespacet ns(transition_system.symbol_table);

  smt2_dect smt2_dec(
    ns,
    "ebmc",
    "Generated by EBMC " EBMC_VERSION,
    "QF_AUFBV",
    smt2_dect::solvert::Z3,
    get_message_handler());

  return do_word_level_bmc(smt2_dec, false);
}

/*******************************************************************\

Function: ebmc_baset::do_cvc4

  Inputs:

 Outputs:

 Purpose:

\*******************************************************************/

int ebmc_baset::do_cvc4()
{
  const namespacet ns(transition_system.symbol_table);

  smt2_dect smt2_dec(
    ns,
    "ebmc",
    "Generated by EBMC " EBMC_VERSION,
    "QF_AUFBV",
    smt2_dect::solvert::CVC4,
    get_message_handler());

  return do_word_level_bmc(smt2_dec, false);
}

/*******************************************************************\

Function: ebmc_baset::do_yices

  Inputs:

 Outputs:

 Purpose:

\*******************************************************************/

int ebmc_baset::do_yices()
{
  const namespacet ns(transition_system.symbol_table);

  smt2_dect smt2_dec(
    ns,
    "ebmc",
    "Generated by EBMC " EBMC_VERSION,
    "QF_AUFBV",
    smt2_dect::solvert::YICES,
    get_message_handler());

  return do_word_level_bmc(smt2_dec, false);
}

/*******************************************************************\

Function: ebmc_baset::do_boolector

  Inputs:

 Outputs:

 Purpose:

\*******************************************************************/

int ebmc_baset::do_boolector()
{
  const namespacet ns(transition_system.symbol_table);

  smt2_dect smt2_dec(
    ns,
    "ebmc",
    "Generated by EBMC " EBMC_VERSION,
    "QF_AUFBV",
    smt2_dect::solvert::BOOLECTOR,
    get_message_handler());

  return do_word_level_bmc(smt2_dec, false);
}

/*******************************************************************\

Function: ebmc_baset::do_sat

  Inputs:

 Outputs:

 Purpose:

\*******************************************************************/

int ebmc_baset::do_sat()
{
  satcheckt satcheck{*message_handler};

  status() << "Using " << satcheck.solver_text() << eom;

  if(cmdline.isset("aig"))
  {
    return do_bit_level_bmc(satcheck, false);
  }
  else
  {
    const namespacet ns(transition_system.symbol_table);
    boolbvt boolbv(ns, satcheck, *message_handler);
    return do_word_level_bmc(boolbv, false);
  }
}

/*******************************************************************\

Function: ebmc_baset::do_prover

  Inputs:

 Outputs:

 Purpose:

\*******************************************************************/

int ebmc_baset::do_prover()
{
#ifdef HAVE_PROVER
  const namespacet ns(transition_system.symbol_table);
  prover_satt prover_sat(ns);
  return do_word_level_bmc(prover_sat, false);
#else
  error() << "Support for prover not linked in" << eom;
  return 1;
#endif
}

/*******************************************************************\

Function: ebmc_baset::do_lifter

  Inputs:

 Outputs:

 Purpose:

\*******************************************************************/

int ebmc_baset::do_lifter()
{
#ifdef HAVE_PROVER
  const namespacet ns(transition_system.symbol_table);
  liftert lifter(ns);
  return do_word_level_bmc(lifter.prop_conv(), false);
#else
  error() << "Support for lifter not linked in" << eom;
  return 1;
#endif
}
